function Visualize(bauraum, gearbox, EC1, EC2, EC3, EC4)

BRaum = patch(bauraum,'FaceColor',       [0 0 1.0], ...
         'EdgeColor',       'none',        ...
         'FaceLighting',    'gouraud',     ...
         'AmbientStrength', 0.15); 
BRaum.FaceAlpha = 0.4 ;          % Interpolate to find face transparency
hold on
view([45 90 135]);
xlabel('X') 
ylabel('Y')
zlabel('Z')
camlight('headlight');
material('default');

patch(gearbox,'FaceColor',       [0.8 0.8 1], ...
     'FaceLighting',    'gouraud',     ...
     'AmbientStrength', 0.15);

patch(EC1,'FaceColor',       [0.8 0 0], ...
     'EdgeColor',       'green',        ...
     'FaceLighting',    'gouraud',     ...
     'AmbientStrength', 0.15);
     
patch(EC2,'FaceColor',       [0 0.8 0], ...
     'EdgeColor',       'red',        ...
     'FaceLighting',    'gouraud',     ...
     'AmbientStrength', 0.15);
 
patch(EC3,'FaceColor',       [1  1 0], ...
     'EdgeColor',       'black',        ...
     'FaceLighting',    'gouraud',     ...
     'AmbientStrength', 0.15);
     
patch(EC4,'FaceColor',       [1 0 1], ...
     'EdgeColor',       'yellow',        ...
     'FaceLighting',    'gouraud',     ...
     'AmbientStrength', 0.15); 


end
